//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MenuList.Base
{
    using System;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;

    public partial class T_App
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public int GroupID { get; set; }
        public string icon { get; set; }
        public Nullable<long> Size { get; set; }
    
        public virtual Group Group { get; set; }

        public static implicit operator T_App(ObservableCollection<T_App> v)
        {
            throw new NotImplementedException();
        }
    }
}
